-- Auto-generated from schema-map-postgres.yaml (map@94ebe6c)
-- engine: postgres
-- table:  books

CREATE TABLE IF NOT EXISTS books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  slug_ci TEXT GENERATED ALWAYS AS (lower(slug)) STORED,
  short_description VARCHAR(512) NULL,
  full_description TEXT NULL,
  price NUMERIC(12,2) NOT NULL DEFAULT 0.00,
  currency CHAR(3) NOT NULL DEFAULT 'EUR',
  author_id BIGINT NOT NULL,
  main_category_id BIGINT NOT NULL,
  isbn VARCHAR(32) NULL,
  language CHAR(5) NULL,
  pages INTEGER NULL,
  publisher VARCHAR(255) NULL,
  published_at DATE NULL,
  sku VARCHAR(64) NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_available BOOLEAN NOT NULL DEFAULT TRUE,
  stock_quantity INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_books_version CHECK (version >= 0),
  deleted_at TIMESTAMPTZ(6) NULL,
  is_live BOOLEAN GENERATED ALWAYS AS (deleted_at IS NULL) STORED,
  CONSTRAINT chk_books_pages      CHECK (pages IS NULL OR pages >= 0),
  CONSTRAINT chk_books_stock_qty  CHECK (stock_quantity >= 0),
  CONSTRAINT chk_books_currency CHECK (currency ~ '^[A-Z]{3}$'),
  CONSTRAINT chk_books_price_nonneg CHECK (price >= 0)
);
